version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-80}:80"
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-3000}:${BACKEND_PORT:-3000}"
    depends_on:
      - database
    environment:
      PORT: ${BACKEND_PORT:-3000}
      DB_HOST: database
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-node}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE:-recipe_book}
    volumes:
      - ./images:/app/public/images  # Mount images directory
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE:-recipe_book}
      MYSQL_USER: ${DB_USER:-node}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:${DB_PORT:-3306}"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro  # Mount MySQL dump file
